//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXzonghejiaofei.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DXzonghejiaofei.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 渠道商编号不可为空,请重新输入! 的本地化字符串。
        /// </summary>
        internal static string ChannelIdErrMsg {
            get {
                return ResourceManager.GetString("ChannelIdErrMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 仍有订单在处理中,确定要关闭程序吗 的本地化字符串。
        /// </summary>
        internal static string CloseMsg {
            get {
                return ResourceManager.GetString("CloseMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 目前仍有业务线程正在关闭,请稍候... 的本地化字符串。
        /// </summary>
        internal static string ClosingMsg {
            get {
                return ResourceManager.GetString("ClosingMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap config {
            get {
                object obj = ResourceManager.GetObject("config", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 程序依赖的文件缺失,请联系开发人员 的本地化字符串。
        /// </summary>
        internal static string DbNotFoundMsg {
            get {
                return ResourceManager.GetString("DbNotFoundMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定要删除上月订单吗?(该操作导致数据不可恢复!) 的本地化字符串。
        /// </summary>
        internal static string DeleteLmOrderTip {
            get {
                return ResourceManager.GetString("DeleteLmOrderTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定要删除上周订单吗?(该操作导致数据不可恢复!) 的本地化字符串。
        /// </summary>
        internal static string DeleteLwOrderTip {
            get {
                return ResourceManager.GetString("DeleteLwOrderTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap pause {
            get {
                object obj = ResourceManager.GetObject("pause", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 请先暂停充值,再关闭应用程序 的本地化字符串。
        /// </summary>
        internal static string PausMsg {
            get {
                return ResourceManager.GetString("PausMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap restart_logo {
            get {
                object obj = ResourceManager.GetObject("restart_logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap save {
            get {
                object obj = ResourceManager.GetObject("save", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 渠道商密钥不可为空,请重新输入! 的本地化字符串。
        /// </summary>
        internal static string SecretKeyErrMsg {
            get {
                return ResourceManager.GetString("SecretKeyErrMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 缴费系统接口地址格式不符合要求,请重新输入! 的本地化字符串。
        /// </summary>
        internal static string ServerUrlErrMsg {
            get {
                return ResourceManager.GetString("ServerUrlErrMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap start {
            get {
                object obj = ResourceManager.GetObject("start", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 提示 的本地化字符串。
        /// </summary>
        internal static string TipMsg {
            get {
                return ResourceManager.GetString("TipMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户密钥不可为空,请重新输入! 的本地化字符串。
        /// </summary>
        internal static string UserKeyErrMsg {
            get {
                return ResourceManager.GetString("UserKeyErrMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户名不可为空,请重新输入! 的本地化字符串。
        /// </summary>
        internal static string UserNameErrMsg {
            get {
                return ResourceManager.GetString("UserNameErrMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户接口地址不可为空,请重新输入! 的本地化字符串。
        /// </summary>
        internal static string UserUrlErrMsg {
            get {
                return ResourceManager.GetString("UserUrlErrMsg", resourceCulture);
            }
        }
    }
}
